login:  # Логин: email или телефон (обязательное поле)
  alexneth93@gmail.com

number_of_resume_to_select: # Какое по счету резюме из имеющихся выбрать (1, 2, 3 и т.д.)
  2 

keywords:  # Ключевые слова (обязательное поле)
  - Аналитик данных Росгосстрах

experience: # Требуемый опыт работы (обязательное поле)
  doesnt_matter: false  # Не имеет значения
  no_experience: false  # Нет опыта
  between_1_and_3: true  # От 1 года до 3 лет
  between_3_and_6: false  # От 3 до 6 лет
  6_and_more: false  # Более 6 лет

sort_by:  # Сортировать выдачу (обязательное поле):
  relevance: true  # по соответствию
  publication_time: false  # по дате изменения
  salary_desc: false  # ао убыванию зарплат
  salary_asc: false  # ао возрастанию зарплаты

output_period:  # Выводить (обязательное поле):
  all_time: false  # за всё время
  month: true  # за месяц
  week: false  # за неделю
  three_days: false  # за последние три дня
  one_day: false  # за сутки

output_size:  # Показывать на странице (обязательное поле): 
  show_20: true
  show_50: false
  show_100: false
