login:  # Логин: email или телефон (обязательное поле)
  beatwad@gmail.com

keywords:  # Ключевые слова (обязательное поле)
  - ML инженер

experience: # Требуемый опыт работы (обязательное поле)
  doesnt_matter: true  # Не имеет значения
  no_experience: false  # Нет опыта
  between_1_and_3: false  # От 1 года до 3 лет
  between_3_and_6: false  # От 3 до 6 лет
  6_and_more: false  # Более 6 лет

sort_by:  # Сортировать выдачу (обязательное поле):
  relevance: true  # по соответствию
  publication_time: false  # по дате изменения
  salary_desc: false  # ао убыванию зарплат
  salary_asc: false  # ао возрастанию зарплаты

output_period:  # Выводить (обязательное поле):
  all_time: true  # за всё время
  month: false  # за месяц
  week: false  # за неделю
  three_days: false  # за последние три дня
  one_day: false  # за сутки

output_size:  # Показывать на странице (обязательное поле): 
  show_20: false
  show_50: true
  show_100: false

llm_model_type: openai  # Тип LLM (обязательное поле)
llm_model: 'gpt-4o-mini'  # Модель LLM (обязательное поле)
